export const SELECT_TOGGLE_MODE = 'SELECT_SWITCH_MODE';
export const SELECT_TOGGLE_FILE = 'SELECT_TOGGLE_FILE';
export const SELECT_CLEAR = 'SELECT_CLEAR';

export const FILESYSTEM_CHANGE_PATH = 'FILESYSTEM_CHANGE_PATH';
export const FILESYSTEM_ADD_FILES = 'FILESYSTEM_ADD_FILES';
export const FILESYSTEM_DELETE_FILES = 'FILESYSTEM_DELETE_FILES';
